name: sugenix
description: A diabetes management system
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  image_picker: ^1.0.4
  permission_handler: ^11.1.0
  geolocator: ^10.1.0
  url_launcher: ^6.2.1
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  provider: ^6.1.1
  http: ^1.1.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  lottie: ^2.7.0
  universal_html: ^2.2.4
  pdf: ^3.10.8
  printing: ^5.13.4
  csv: ^5.0.2
  razorpay_flutter: ^1.3.1

dependency_overrides:
  firebase_auth_web: ^6.0.4
  cloud_firestore_web: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/sugenix_logo.png.png
  
  generate: true
